package org.desafio.desafioback.exception;

public class ContatoNaoEncontradoException extends RuntimeException {

    public ContatoNaoEncontradoException(String message) {
        super(message);
    }
}
